### ISSUE TITLE
Export and expose the options interface

### ISSUE THREAD

**Issue by Sec-ant** [nene/prettier-plugin-sql-cst#17]
Would you mind exposing the options interface so this can be used in `prettier-plugin-embed`? This is also helpful if users are using JSDoc to get type hints when configuring prettier, or using prettier programmatically in a TypeScript project.

https://github.com/nene/prettier-plugin-sql-cst/blob/57f988d5d7365d20214d63d7406bef56d581a985/src/options.ts#L4-L7

And apparently they have [default values](https://github.com/nene/prettier-plugin-sql-cst?tab=readme-ov-file#configuration) so the properties should also be optional?

```ts
export interface SqlPluginOptions {
  sqlKeywordCase?: "preserve" | "upper" | "lower";
  sqlParamTypes?: NonNullable<CstParserOptions["paramTypes"]>;
}
```

**Comment by nene** [comment]
Yeah, why not.

I exposed the `SqlPluginOptions` interface in 9.0.1 release.

You can wrap it in `Partial<>` if you need the fields to be optional. I'm internally using the non-optional fields variant because prettier fills in the default values. Not sure how exactly it's going to be used externally. Like one probably wants to combine it with the prettier builtin options interface.
